/*
 * =====================================================================
 *  IshizukiTech LLC — SLM Integration Framework
 *  ---------------------------------------------------------------------
 *  File: SurveyFileName.kt
 *  Author: Shu Ishizuki (石附 支)
 *  License: MIT License
 *  © 2025 IshizukiTech LLC. All rights reserved.
 * =====================================================================
 *
 *  Summary:
 *  ---------------------------------------------------------------------
 *  UUID-aware survey export naming helpers (single naming authority).
 *
 *  Design goals:
 *   • Always embed the run UUID when available and valid.
 *   • Preserve legacy call sites via overloads (session-based).
 *   • Avoid overload ambiguity caused by default parameters.
 *   • Enforce safe filename segments and full-name length constraints.
 *   • Use UTC timestamps for cross-device stable ordering.
 *   • Centralize naming rules for JSON and voice exports.
 *
 *  Notes:
 *   • This file intentionally does not touch filesystem I/O.
 *     Uniqueness on-disk (collisions) should still be handled by the caller
 *     (e.g., ExportUtils.makeUniqueFile()).
 * =====================================================================
 */

@file:Suppress("MemberVisibilityCanBePrivate", "unused")

package com.negi.survey.utils

import java.security.SecureRandom
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone
import kotlin.math.max

/* ============================================================
 * Types
 * ============================================================ */

/**
 * Strongly-typed wrapper for a survey run UUID used to prevent overload
 * ambiguity with legacy APIs.
 */
@JvmInline
value class SurveyUuid(val value: String)

/* ============================================================
 * Constants
 * ============================================================ */

private const val TRIM_STEP = 12
private const val MIN_PART_LEN = 12
private const val MAX_TRIM_PASSES = 20

/** File extension constants. */
private const val EXT_JSON = "json"
private const val EXT_WAV = "wav"

/**
 * Conservative cap for the full file name length (including extension).
 * Many filesystems allow 255 bytes, but keeping lower reduces surprises.
 */
private const val MAX_FILE_NAME_LEN = 180

/**
 * Conservative cap for individual segments (prefix/uuid/qid/etc).
 * The builder additionally clamps the final assembled name.
 */
private const val MAX_SEGMENT_LEN = 80

/**
 * UTC timestamp pattern that is filesystem-friendly and lexicographically sortable.
 * Example: 2025-12-05_14-32-08.123Z
 */
private const val TS_PATTERN_UTC = "yyyy-MM-dd_HH-mm-ss.SSS'Z'"

/**
 * Regex that matches the exact timestamp format generated by [timeStampUtc].
 */
private val TS_UTC_REGEX = Regex("""^\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}\.\d{3}Z$""")

/**
 * Segment whitelist:
 * - Keep only A-Z, a-z, 0-9, dot, underscore, and hyphen.
 * - Replace other runs with a single underscore.
 */
private val SEGMENT_SANITIZER = Regex("[^A-Za-z0-9._-]+")

/**
 * UUID validator (accept lowercase after normalization).
 * Intentionally strict to prevent random strings from being treated as UUIDs.
 */
private val UUID_REGEX = Regex(
    "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
)

/** Secure RNG for optional suffix. */
private val RNG = SecureRandom()

/* ============================================================
 * Public: Survey JSON file name
 * ============================================================ */

/**
 * Build a stable survey JSON file name that embeds the run UUID.
 *
 * Primary format:
 *   <prefix>_<surveyUuid>_<timestamp>.json
 */
fun buildSurveyFileName(
    surveyId: String,
    prefix: String = "survey",
    stamp: String? = null,
    nowMillis: Long = System.currentTimeMillis(),
    addRandomSuffix: Boolean = false
): String {
    val pfx = safeSegment(prefix)
    val ts = safeStampOrNow(stamp, nowMillis)
    val uuid = normalizeUuidOrNull(surveyId)?.let { safeSegment(it) } ?: "unknown"
    val suf = if (addRandomSuffix) safeSegment(shortToken()) else null

    // Keep timestamp always last for simpler trimming rules.
    return assembleFileName(
        ext = EXT_JSON,
        parts = listOfNotNull(pfx, uuid, suf, ts)
    )
}

/**
 * Legacy-friendly overload for call sites that still name by session id.
 *
 * Legacy format:
 *   <prefix>_session<sessionId>_<timestamp>.json
 */
fun buildSurveyFileName(
    sessionId: Int,
    prefix: String = "survey",
    stamp: String? = null,
    nowMillis: Long = System.currentTimeMillis(),
    addRandomSuffix: Boolean = false
): String {
    val pfx = safeSegment(prefix)
    val ts = safeStampOrNow(stamp, nowMillis)
    val sid = "session${sessionId.coerceAtLeast(0)}"
    val suf = if (addRandomSuffix) safeSegment(shortToken()) else null

    return assembleFileName(
        ext = EXT_JSON,
        parts = listOfNotNull(pfx, sid, suf, ts)
    )
}

/**
 * Bridge overload: session counter + typed UUID wrapper.
 */
fun buildSurveyFileName(
    sessionId: Int,
    surveyUuid: SurveyUuid,
    prefix: String = "survey",
    stamp: String? = null,
    nowMillis: Long = System.currentTimeMillis(),
    addRandomSuffix: Boolean = false
): String {
    val normalized = normalizeUuidOrNull(surveyUuid.value)
    return if (!normalized.isNullOrBlank()) {
        buildSurveyFileName(
            surveyId = normalized,
            prefix = prefix,
            stamp = stamp,
            nowMillis = nowMillis,
            addRandomSuffix = addRandomSuffix
        )
    } else {
        buildSurveyFileName(
            sessionId = sessionId,
            prefix = prefix,
            stamp = stamp,
            nowMillis = nowMillis,
            addRandomSuffix = addRandomSuffix
        )
    }
}

/* ============================================================
 * Public: Voice WAV file name
 * ============================================================ */

/**
 * Build a stable voice WAV file name that embeds UUID and question id.
 *
 * Format:
 *   <prefix>_<surveyUuid>_<questionId>_<timestamp>.wav
 */
fun buildVoiceFileName(
    surveyUuid: String,
    questionId: String?,
    prefix: String = "voice",
    stamp: String? = null,
    nowMillis: Long = System.currentTimeMillis(),
    addRandomSuffix: Boolean = false
): String {
    val pfx = safeSegment(prefix)
    val ts = safeStampOrNow(stamp, nowMillis)

    val uuid = normalizeUuidOrNull(surveyUuid)?.let { safeSegment(it) } ?: "unknown"
    val qid = safeSegment(questionId ?: "unknown")

    val suf = if (addRandomSuffix) safeSegment(shortToken()) else null

    return assembleFileName(
        ext = EXT_WAV,
        parts = listOfNotNull(pfx, uuid, qid, suf, ts)
    )
}

/**
 * Voice naming overload for strongly-typed UUID wrapper.
 */
fun buildVoiceFileName(
    surveyUuid: SurveyUuid,
    questionId: String?,
    prefix: String = "voice",
    stamp: String? = null,
    nowMillis: Long = System.currentTimeMillis(),
    addRandomSuffix: Boolean = false
): String {
    return buildVoiceFileName(
        surveyUuid = surveyUuid.value,
        questionId = questionId,
        prefix = prefix,
        stamp = stamp,
        nowMillis = nowMillis,
        addRandomSuffix = addRandomSuffix
    )
}

/* ============================================================
 * Timestamp + normalization + assembly
 * ============================================================ */

/**
 * Create a filename-friendly UTC timestamp string.
 */
private fun timeStampUtc(nowMillis: Long): String {
    val fmt = SimpleDateFormat(TS_PATTERN_UTC, Locale.US).apply {
        timeZone = TimeZone.getTimeZone("UTC")
    }
    return fmt.format(Date(nowMillis))
}

/**
 * Sanitize/validate incoming stamp:
 * - If null/blank => generate from [nowMillis]
 * - Else => sanitize as segment, but if it becomes "unknown" => fallback to now
 */
private fun safeStampOrNow(stamp: String?, nowMillis: Long): String {
    if (stamp.isNullOrBlank()) return safeSegment(timeStampUtc(nowMillis))
    val cleaned = safeSegment(stamp)
    return if (cleaned == "unknown") safeSegment(timeStampUtc(nowMillis)) else cleaned
}

/**
 * Normalize UUID strings:
 * - Trim, remove surrounding braces, lower-case
 * - Validate against UUID-like regex
 *
 * Returns null when invalid.
 */
private fun normalizeUuidOrNull(raw: String?): String? {
    if (raw.isNullOrBlank()) return null
    val s = raw.trim()
        .removePrefix("{")
        .removeSuffix("}")
        .lowercase(Locale.US)

    return if (UUID_REGEX.matches(s)) s else null
}

/**
 * Sanitize a filename segment to avoid path traversal and unstable characters.
 *
 * Rules:
 * - Keep only A-Z, a-z, 0-9, dot, underscore, and hyphen.
 * - Replace all other character runs with a single underscore.
 * - Trim leading/trailing underscores.
 * - Enforce a conservative length limit.
 */
private fun safeSegment(raw: String): String {
    return raw
        .trim()
        .replace(SEGMENT_SANITIZER, "_")
        .trim('_')
        .take(MAX_SEGMENT_LEN)
        .ifBlank { "unknown" }
}

/**
 * Assemble "<part>_<part>_... .<ext>" while enforcing a full-name length cap.
 *
 * Strategy:
 * - Join parts with "_" and append ".ext".
 * - If too long, progressively shrink the longest non-timestamp segments using
 *   a middle-ellipsis trim (keeps both head and tail).
 * - As a last resort, hard-trim the base name to fit.
 */
private fun assembleFileName(ext: String, parts: List<String>): String {
    val cleanExt = safeSegment(ext).ifBlank { "dat" }

    val baseParts = parts.map { safeSegment(it) }.toMutableList()
    var base = baseParts.joinToString("_")
    var full = "$base.$cleanExt"

    if (full.length <= MAX_FILE_NAME_LEN) return full

    fun isExactTimestamp(s: String): Boolean = TS_UTC_REGEX.matches(s)

    var pass = 0
    while (full.length > MAX_FILE_NAME_LEN && pass < MAX_TRIM_PASSES) {
        pass++

        // Find the best candidate to shrink:
        // - Prefer the longest part
        // - Avoid shrinking the exact timestamp (always last in our parts)
        var bestIdx = -1
        var bestLen = 0
        for (i in baseParts.indices) {
            val p = baseParts[i]
            if (isExactTimestamp(p)) continue
            if (p.length > bestLen) {
                bestLen = p.length
                bestIdx = i
            }
        }

        if (bestIdx == -1 || bestLen <= MIN_PART_LEN) break

        val newLen = (bestLen - TRIM_STEP).coerceAtLeast(MIN_PART_LEN)
        baseParts[bestIdx] = baseParts[bestIdx].middleEllipsis(newLen)

        base = baseParts.joinToString("_")
        full = "$base.$cleanExt"
    }

    if (full.length <= MAX_FILE_NAME_LEN) return full

    // Last resort: hard-trim the base name to fit.
    val maxBaseLen = (MAX_FILE_NAME_LEN - (cleanExt.length + 1)).coerceAtLeast(8)
    val hard = base.take(maxBaseLen)
    return "$hard.$cleanExt"
}

/**
 * Middle-ellipsis trimming to preserve both head and tail.
 * Example: "abcdefghij" -> "abcd…hij" depending on target length.
 */
private fun String.middleEllipsis(targetLen: Int): String {
    val t = targetLen.coerceAtLeast(1)
    if (length <= t) return this
    if (t <= 3) return take(t)

    val ellipsis = "…"
    val keep = t - ellipsis.length
    val head = max(1, keep / 2)
    val tail = max(1, keep - head)

    return take(head) + ellipsis + takeLast(tail)
}

/**
 * Short random token for optional collision resistance.
 */
private fun shortToken(): String {
    val b = ByteArray(4) // 8 hex chars
    RNG.nextBytes(b)
    return b.toHexLower()
}

private fun ByteArray.toHexLower(): String {
    val out = CharArray(size * 2)
    val hex = "0123456789abcdef"
    var i = 0
    for (bb in this) {
        val v = bb.toInt() and 0xFF
        out[i++] = hex[v ushr 4]
        out[i++] = hex[v and 0x0F]
    }
    return String(out)
}
